### ISSUE TITLE
Audio files are not played properly

### ISSUE THREAD

**Issue by ThomasKinder11** [ThomasKinder11/imc#4]
WHen playing mp3 this error comes:
 Traceback (most recent call last):
   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
   File "/home/thomas/Documents/isha-pi/imc/player_core.py", line 207, in _playlistWork
     entry = playlist[str(entryId)]
 KeyError: '0'

**Comment by ThomasKinder11** [comment]
There was a problem in the File List viewer where we used "audio" as coonfig selector but audio had been chagned to music
